version: '3.8'
services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: Nothingbetterthanal
      MYSQL_USER: camillia
      MYSQL_PASSWORD: xyz123
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8080:80'
    depends_on:
      - mysql-db
    environment:
      - PMA_HOST=mysql-db
volumes:
  mysql-data:
    driver: local
